"""
Unit tests for the static data files in mistral-it-agent/data/.

Covers: schema integrity of raw_tickets.json, kb.json, internal_kb.json,
        escalation_policy.json, and (if present) the JSONL split files.

NOT tested here:
  - Data quality / realism of ticket text — subjective and not machine-verifiable.
  - Label distribution balance — the train/val/test split is a one-time artifact;
    the exact proportions are verified manually when 01_data_prep.ipynb is run.
  - The contents of finetune_config.json or classifier_model_id.txt — those are
    generated by notebooks 01 and 02 and are not committed to source control.
"""

import json
from pathlib import Path

import pytest

_DATA_DIR = Path(__file__).parent.parent / "data"

INTENT_LABELS = frozenset({
    "access_request",
    "security_incident",
    "hardware_issue",
    "software_issue",
    "onboarding",
    "payments_incident",
    "expense_request",
    "general_question",
})


# ---------------------------------------------------------------------------
# raw_tickets.json
# ---------------------------------------------------------------------------

class TestRawTickets:

    def test_raw_tickets_have_required_fields(self, data_files):
        tickets = data_files["raw_tickets"]
        required = {"id", "text", "intent", "priority"}

        for ticket in tickets:
            missing = required - ticket.keys()
            assert not missing, (
                f"Ticket {ticket.get('id', '?')} is missing fields: {missing}"
            )

    def test_raw_tickets_intent_categories(self, data_files):
        for ticket in data_files["raw_tickets"]:
            assert ticket["intent"] in INTENT_LABELS, (
                f"Ticket {ticket['id']} has unknown intent '{ticket['intent']}'. "
                f"Valid labels: {sorted(INTENT_LABELS)}"
            )

    def test_raw_tickets_priority_values(self, data_files):
        valid_priorities = {"P1", "P2", "P3"}
        for ticket in data_files["raw_tickets"]:
            assert ticket["priority"] in valid_priorities, (
                f"Ticket {ticket['id']} has invalid priority '{ticket['priority']}'"
            )

    def test_raw_tickets_all_intents_represented(self, data_files):
        """Every intent category must appear at least once in the ticket corpus."""
        present = {t["intent"] for t in data_files["raw_tickets"]}
        missing = INTENT_LABELS - present
        assert not missing, f"No tickets for intent(s): {missing}"

    def test_raw_tickets_ids_are_unique(self, data_files):
        ids = [t["id"] for t in data_files["raw_tickets"]]
        assert len(ids) == len(set(ids)), "Duplicate ticket IDs detected"

    def test_raw_tickets_text_is_non_empty(self, data_files):
        for ticket in data_files["raw_tickets"]:
            assert ticket["text"].strip(), (
                f"Ticket {ticket['id']} has empty text"
            )


# ---------------------------------------------------------------------------
# kb.json and internal_kb.json
# ---------------------------------------------------------------------------

class TestKnowledgeBaseArticles:

    @pytest.mark.parametrize("kb_key", ["kb", "internal_kb"])
    def test_kb_articles_have_required_fields(self, data_files, kb_key):
        articles = data_files[kb_key]["articles"]
        assert len(articles) > 0, f"{kb_key} has no articles"

        for article in articles:
            assert "title" in article, f"Article {article.get('id')} missing 'title'"
            # Field is named 'content' in both kb.json and internal_kb.json
            assert "content" in article, f"Article {article.get('id')} missing 'content'"
            assert article["title"].strip(), f"Article {article.get('id')} has empty title"
            assert article["content"].strip(), f"Article {article.get('id')} has empty content"

    @pytest.mark.parametrize("kb_key", ["kb", "internal_kb"])
    def test_kb_article_ids_are_unique(self, data_files, kb_key):
        ids = [a["id"] for a in data_files[kb_key]["articles"]]
        assert len(ids) == len(set(ids)), f"Duplicate article IDs in {kb_key}"

    def test_internal_kb_uses_vkb_prefix(self, data_files):
        for article in data_files["internal_kb"]["articles"]:
            assert article["id"].startswith("VKB-"), (
                f"Internal KB article '{article['id']}' should start with 'VKB-'"
            )

    def test_generic_kb_uses_kb_prefix(self, data_files):
        for article in data_files["kb"]["articles"]:
            assert article["id"].startswith("KB-"), (
                f"Generic KB article '{article['id']}' should start with 'KB-'"
            )


# ---------------------------------------------------------------------------
# escalation_policy.json
# ---------------------------------------------------------------------------

class TestEscalationPolicy:

    def test_escalation_policy_covers_all_intents(self, data_files):
        policy = data_files["escalation_policy"]
        covered = {p["intent"] for p in policy["escalation_paths"]}
        missing = INTENT_LABELS - covered
        assert not missing, (
            f"escalation_policy.json is missing entries for: {missing}"
        )

    def test_escalation_policy_each_path_has_tiers(self, data_files):
        for path in data_files["escalation_policy"]["escalation_paths"]:
            assert "tiers" in path, f"No tiers for intent '{path['intent']}'"
            assert len(path["tiers"]) >= 1, (
                f"Intent '{path['intent']}' must have at least one escalation tier"
            )

    def test_escalation_policy_tiers_have_contact(self, data_files):
        for path in data_files["escalation_policy"]["escalation_paths"]:
            for tier in path["tiers"]:
                assert "contact" in tier or "slack" in tier, (
                    f"Tier {tier.get('tier')} of '{path['intent']}' has no contact info"
                )

    def test_escalation_policy_payments_incident_is_always_p1(self, data_files):
        """The escalation policy must document that all payments incidents are P1."""
        payments = next(
            p for p in data_files["escalation_policy"]["escalation_paths"]
            if p["intent"] == "payments_incident"
        )
        sla_text = json.dumps(payments.get("sla_overrides", {}))
        assert "P1" in sla_text


# ---------------------------------------------------------------------------
# JSONL split files (generated by 01_data_prep.ipynb — may not exist)
# ---------------------------------------------------------------------------

class TestJsonlSplits:

    @pytest.mark.parametrize("filename", ["train.jsonl", "val.jsonl", "test.jsonl"])
    def test_jsonl_splits_if_exist(self, filename):
        path = _DATA_DIR / filename
        if not path.exists():
            pytest.skip(f"{filename} not yet generated — run 01_data_prep.ipynb first")

        with open(path) as f:
            lines = [line.strip() for line in f if line.strip()]

        assert len(lines) > 0, f"{filename} is empty"

        for i, line in enumerate(lines, start=1):
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                pytest.fail(f"{filename} line {i} is not valid JSON: {exc}")

            assert "text" in record, (
                f"{filename} line {i} missing 'text' key"
            )
            assert "labels" in record, (
                f"{filename} line {i} missing 'labels' key"
            )
            assert "intent" in record["labels"], (
                f"{filename} line {i} missing 'labels.intent' key"
            )
            assert record["labels"]["intent"] in INTENT_LABELS, (
                f"{filename} line {i} has unknown intent '{record['labels']['intent']}'"
            )
